baseURL = "https://androidoss.now.sh"
languageCode = "iw-IL"
title = "אנדרוידוס - בלוג על אנדרואיד בעברית"
theme = "journal"

disqusShortname = "androidoss"
pygmentsCodefences = true
pygmentsStyle = "dracula"

[params]
    primaryColor = "#ffee58"
    description = "בלוג למפתחי אנדרואיד מתחילים על פיתוח אפליקציות לאנדרואיד בעברית"