baseURL = "https://androidoss.now.sh"
languageCode = "iw-IL"
title = "אנדרואידוס - בלוג על אנדרואיד בעברית"
theme = "journal"

disqusShortname = "androidoss"
googleAnalytics = "UA-151592580-1"
pygmentsCodefences = true
pygmentsStyle = "dracula"

[params]
    primaryColor = "#ffee58"
    description = "בלוג למפתחי אנדרואיד מתחילים על פיתוח אפליקציות לאנדרואיד בעברית"