baseURL = "https://androidoss.now.sh"
languageCode = "iw-IL"
title = "אנדרוידוס - בלוג על אנדרואיד בעברית"
description = "בלוג למפתחי אנדרואיד בעברית"
theme = "journal"

disqusShortname = "androidoss"
pygmentsCodefences = true
pygmentsStyle = "dracula"